# Generated by Django 5.2.4 on 2025-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_call',
            field=models.BooleanField(default=False, help_text='Is this user currently the primary on-call contact?'),
        ),
    ]
