# Generated by Django 5.2.4 on 2025-07-31 16:12

import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('COMMENT', 'Comment'), ('STATE_CHANGE', 'State Change'), ('ASSIGNMENT', 'Assignment'), ('ATTACHMENT', 'Attachment')], default='COMMENT', max_length=20)),
                ('entry', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('number', models.CharField(default=incidents.models.get_next_incident_number, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low')], default='3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
